FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
EXPOSE 5001
ENV ASPNETCORE_URLS=http://*:5001

WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "ItemService.dll" ]